-- Names chosen to exercise fuzzy matching, plus unrelated companies that should score low.
-- normalised_name is filled by the trigger.

TRUNCATE company RESTART IDENTITY;

INSERT INTO company (company_name) VALUES
    ('Stephen Engineering Limited'),
    ('Steven Engineering Ltd'),
    ('Stefen Engineering'),
    ('Stephens Engineering'),
    ('Stevenson Engineering'),
    ('Stephanie Engineering Limited'),
    ('Stephen Electrical Limited'),
    ('O''Reilly Technologies Limited'),
    ('OReilly Technology Ltd'),
    ('O Riley Technologies'),
    ('O''Reilly Technical Services'),
    ('O''Reilly Construction Limited'),
    ('McDonnell Construction'),
    ('MacDonnell Construction'),
    ('McDonald Construction'),
    ('McDonnell Constructors Ltd'),
    ('Macdonald Building Company'),
    ('Acme Software Limited'),
    ('ACME Software Ltd'),
    ('Acme Soft Inc'),
    ('Acme Hardware Limited'),
    ('Appletree Technologies'),
    ('Apple Technologies'),
    ('Appletree Consulting Ltd'),
    ('Pineapple Technologies'),
    ('Mooney Consulting Limited'),
    ('Mooney Construction Ltd'),
    ('Mooney Consultants'),
    ('Mooney & Sons Consulting'),
    ('Harbour View Hotels Limited'),
    ('Harbor View Hotel Ltd'),
    ('Global Freight Limited'),
    ('Global Freights Ltd'),
    ('Quinn & Co Solicitors'),
    ('Quinn and Company Solicitors'),
    ('Zenith Logistics Limited'),
    ('Bluebird Packaging Ltd'),
    ('Northwind Traders'),
    ('Fabrikam Industries'),
    ('Contoso Retail Limited'),
    ('Initech Solutions Ltd'),
    ('Umbrella Health PLC'),
    ('Vandelay Industries'),
    ('Dunder Mifflin Paper Company'),
    ('Pied Piper Limited'),
    ('Hooli Technologies'),
    ('Wonka Confectionery Ltd'),
    ('Gringotts Bank'),
    ('Prestige Worldwide'),
    ('Bluth Company'),
    ('Oscorp Research'),
    ('Massive Dynamic');
