-- Extra names and labelled cases. Safe to run more than once.

INSERT INTO company (company_name)
SELECT name
FROM (VALUES
    ('Smyth & Sons Builders'),
    ('Smith and Sons Building'),
    ('Smythe Sons Construction'),
    ('Catherine Walsh Consulting'),
    ('Katherine Walsh Consultants'),
    ('Kathryn Walsh Consulting'),
    ('Geoff Patterson Motors'),
    ('Jeff Patterson Motor Co'),
    ('Philip Clarke Solicitors'),
    ('Phillip Clarke Solicitor'),
    ('Colour Lab Printing'),
    ('Color Lab Print Ltd'),
    ('Centre Point Estates'),
    ('Center Point Estate'),
    ('Byrne Transport Limited'),
    ('Burnes Transport Ltd'),
    ('Burns Haulage'),
    ('O''Brien Electrical'),
    ('Obrien Electric Ltd'),
    ('O Brien Electrical'),
    ('Sheikh Trading Limited'),
    ('Shaikh Trade Ltd'),
    ('Andersen Windows Ltd'),
    ('Anderson Window Company'),
    ('Nielsen Analytics'),
    ('Neilson Analytic Ltd'),
    ('Fitzgerald Surveying'),
    ('Fitz Gerald Surveys Ltd'),
    ('De Souza Logistics'),
    ('Desouza Logistic Limited'),
    ('Harbourmaster Marine'),
    ('Harbor Master Marina Ltd'),
    ('Knightbridge Property'),
    ('Knightsbridge Properties Ltd'),
    ('Aldridge Fabrication'),
    ('Eldridge Fabrications Ltd'),
    ('Northshore Fisheries'),
    ('North Shore Fishery Ltd'),
    ('Blackwater Chemicals'),
    ('Greenfield Dairies'),
    ('Redoak Timber'),
    ('Silverline Couriers'),
    ('Copperfield Mining'),
    ('Ironclad Security'),
    ('Paperkite Design'),
    ('Larkspur Hotels'),
    ('Wavecrest Insurance'),
    ('Summit Ridge Energy'),
    ('Lowland Aggregates'),
    ('Highgate Bakery'),
    ('Millhouse Textiles'),
    ('Brookside Veterinary'),
    ('Ashford Legal'),
    ('Penrose Architecture'),
    ('Calder Engineering Works'),
    ('Hargreave Pumps'),
    ('Yates Agricultural'),
    ('Phelan Cold Storage'),
    ('Donnelly Waste'),
    ('Kavanagh Printing'),
    ('Lawlor Scaffolding'),
    ('Keane Glass'),
    ('Raftery Stone'),
    ('Tormey Plant Hire'),
    ('O''Connell Fuels'),
    ('Walsh Refrigeration'),
    ('Brennan Roofing'),
    ('Hayes Electrical Wholesale'),
    ('Nolan Precision'),
    ('Carroll Packaging'),
    ('Daly Water Treatment'),
    ('Foley Medical'),
    ('Griffin Aviation'),
    ('Hughes Rail'),
    ('Ivers Lighting'),
    ('Joyce Maritime'),
    ('Kennedy Quarry'),
    ('Lennon Plastics'),
    ('Maguire Lifts'),
    ('Neville Optics'),
    ('O''Sullivan Dairy'),
    ('Power Hydraulics'),
    ('Quigley Ceramics'),
    ('Redmond Alloys'),
    ('Scanlon Bearings'),
    ('Tierney Composites'),
    ('Underwood Valves'),
    ('Vaughan Castings'),
    ('Whelan Fasteners'),
    ('Youngblood Coatings'),
    ('Zephyr Turbines')
) AS extra(name)
WHERE NOT EXISTS (
    SELECT 1 FROM company AS existing WHERE existing.company_name = extra.name
);

TRUNCATE match_case RESTART IDENTITY;

INSERT INTO match_case (search_name, expected_name, should_match, minimum_score, maximum_score, rival_name, note) VALUES
    ('Steven Engineering Ltd', 'Stephen Engineering Limited', true, 80, NULL, 'Zenith Logistics Limited', 'Stephen and Steven should outrank an unrelated company'),
    ('Stefen Engineering', 'Stephen Engineering Limited', true, 80, NULL, NULL, 'Stefen is a spelling variant of Stephen'),
    ('OReilly Technology Ltd', 'O''Reilly Technologies Limited', true, 80, NULL, NULL, 'Apostrophe and Ltd/Limited should collapse'),
    ('O Riley Technologies', 'O''Reilly Technologies Limited', true, 75, NULL, NULL, 'Split initial still belongs with O''Reilly'),
    ('McDonnell Construction', 'MacDonnell Construction', true, 85, NULL, 'McDonald Construction', 'MacDonnell should beat the McDonald false friend'),
    ('ACME Software Ltd', 'Acme Software Limited', true, 100, 100, NULL, 'Same name once suffixes and case are removed'),
    ('Appletree Technologies', 'Apple Technologies', true, 50, 94, NULL, 'Apple is related but must not look exact'),
    ('Mooney Consulting Limited', 'Mooney Construction Ltd', true, 70, NULL, NULL, 'Shared surname, different trade'),
    ('Smyth & Sons Builders', 'Smith and Sons Building', true, 70, NULL, NULL, 'Smyth/Smith and &/and'),
    ('Catherine Walsh Consulting', 'Katherine Walsh Consultants', true, 75, NULL, NULL, 'Catherine and Katherine'),
    ('Geoff Patterson Motors', 'Jeff Patterson Motor Co', true, 70, NULL, NULL, 'Geoff and Jeff'),
    ('Colour Lab Printing', 'Color Lab Print Ltd', true, 70, NULL, NULL, 'Colour and Color'),
    ('O''Brien Electrical', 'Obrien Electric Ltd', true, 75, NULL, NULL, 'O''Brien and Obrien'),
    ('Stephen Engineering Limited', 'Zenith Logistics Limited', false, 50, NULL, NULL, 'Unrelated names stay under 50'),
    ('Acme Software Limited', 'Pineapple Technologies', false, 50, NULL, NULL, 'A shared ending is not enough');
